Refactor/main component
sendOwlOrganization/SendOwl-Web pull request #12
Opened 2022-05-07 12:33 UTC by LeeSuHa98

- [ ] MainContent.stories.tsx 에서 카테고리 리스트 확인 
- [ ] Main/MainContent 로 수정 : Main 내 컨텐츠 리스트
        - api 연동 필요
- [ ] Header : LoginButton 연결
- [ ] Header/HeaderMenu 추출

2022-05-08 18:00 UTC, leesangb requested changes

2022-05-09 07:36 UTC, LeeSuHa98 commented on src/components/board-category-list/BoardCategoryPostList.tsx
> +                    <a>
네 !
전체적으로 급하게 커밋하느라 잔실수들이 많네요ㅠㅠ 다음 PR 부턴 신경쓰도록 하겠습니다 !!

2022-05-09 07:39 UTC, LeeSuHa98 commented on src/components/global/Header.tsx
> +                                <ColorButton style={{ borderRadius: 0 }}>
너무 좋은 것 같아요! 컬러 등 동일하게 스타일 적용되는 부분들은 테마옵션에 추가하는 방식으로 하면 되겠네용

2022-05-20 09:33 UTC, leesangb requested changes

2022-05-20 09:33 UTC, leesangb commented on src/api/index.ts
>              const { response }: ResponseDto<T> = await data.json();
```ts
const response: T = await data.json(); 
```
으로 바꿔도 될것같아요

2022-05-20 10:51 UTC, LeeSuHa98 commented on src/api/index.ts
>              const { response }: ResponseDto<T> = await data.json();
수정했습니다 !

2022-05-20 11:18 UTC, leesangb approved these changes

2022-05-20 11:56 UTC, merged