Refactor/main page
sendOwlOrganization/SendOwl-Web pull request #16
Opened 2022-07-26 10:57 UTC by LeeSuHa98

- [ ] 메인 페이지 디자인 반영
- [ ] 아토믹 디자인 반영
- [ ] 메인 페이지 내 컴포넌트 분리

추가 필요 사항
* 사이드바 chart 추가 ( 현재는 이미지 데이터 )
* 반응형 앱 변경 필요
* 카테고리 및 사용자 데이터 api fetch

2022-07-26 14:57 UTC, leesangb requested changes

2022-07-26 14:57 UTC, leesangb commented on src/component/atoms/BoxGradient.tsx
> +                borderRadius={border}
props를 통해서 변경사항이 없는 css는 `styled`로 `OutlinedButton`처럼 컴포넌트를 만든 후 사용하는 것도 좋을 것 같아요!
https://mui.com/system/basics/#performance-tradeoff
보시면 성능 차이도 은근 나는 것 같더라구요!

2022-07-26 14:57 UTC, leesangb commented on src/component/molecules/ContentList.tsx
> +                sx={{
`BoxGradient`과 동일

2022-07-26 14:57 UTC, leesangb commented on src/component/molecules/ContentListTitle.tsx
> +                        <a style={{ fontSize: '12px', fontWeight: '400' }}>
인라인 스타일은 쓰지 않는게 좋을것같아요! `styled`로 감싸서 컴포넌트를 만들고 `Link`에 `passHref` props를 추가하면 좋을것같습니다

2022-07-26 14:57 UTC, leesangb commented on src/component/molecules/CreatePost.tsx
> +import enfj from '../../../public/images/enfj.png';
`public`폴더에 있는 이미지는 import 없이 `src='/images/enfj.png'`로 변경해도 될거에요!

2022-07-26 14:57 UTC, leesangb commented on src/component/organisms/chart/Mbti.tsx
> +import mainGraph from '../../../../public/images/mainGraph.png';
`CreatePost`와 동일

2022-07-26 14:57 UTC, leesangb commented on src/components/global/Header.tsx
> +import logo from '../../../public/images/logo.png';
`CreatePost`와 동일

2022-07-27 03:48 UTC, LeeSuHa98 commented on src/component/atoms/BoxGradient.tsx
> +                borderRadius={border}
오 좋아요 !! 수정했습니당 !

2022-07-27 03:49 UTC, LeeSuHa98 commented on src/component/molecules/CreatePost.tsx
> +import enfj from '../../../public/images/enfj.png';
이미지 src 수정 모두 완료했습니다 ~

2022-07-27 04:10 UTC, leesangb approved these changes

2022-07-27 04:10 UTC, merged