Carousel 기능 수정
sendOwlOrganization/SendOwl-Web pull request #38
Opened 2022-09-17 19:33 UTC by LeeSuHa98

- [ ] ImageOptimize 컴포넌트 추가 ( device 별 이미지 크기가 정해지지 않아서 따로 추가하진 않았습니다 ! )
       ㄴ 수정 필요
- [ ] Pagination 컴포넌트 추가

![ ](https://user-images.githubusercontent.com/40999647/190873584-468c3e22-459e-4b13-ab3c-2a58543d962e.gif)
 테스트 : https://www.chromatic.com/component?appId=62fe0ad986470e80b0a6aace&csfId=components-carousel-carousel&k=63261e17b55fe4a36d26553b-1200-interactive-true&h=4&b=-1

2022-09-17 23:09 UTC, leesangb requested changes

2022-09-17 23:09 UTC, leesangb commented on src/components/carousel/carousel/Carousel.tsx
> +                {data.map((element, index) => (
`index`를 쓰지 않으면 삭제해도 될 것 같아요!

2022-09-17 23:09 UTC, leesangb commented on src/components/carousel/imageOptimize.tsx
> +    images: string;
`images`가 복수형이다 보니 `array`로 착각할 수도 있을 것 같아요! 
`image` 또는 `src`로 쓰면 어떨까요?

2022-09-17 23:09 UTC, leesangb commented on src/components/carousel/carousel/Carousel.tsx
> +    check?: boolean;
`check`이라는 네이밍이 어떤 것을 체크한다는 것 같아서 혼동을 줄 수도 있어보여요!
`showPagination` 이런식으로 바꿔서 보다 정확한 역할을 알려주는게 좋을 것 같아요!

2022-09-17 23:09 UTC, leesangb commented on src/components/carousel/carousel/Carousel.tsx
> +    images: string;
`ImageOptimize`와 동일합니다!

2022-09-17 23:09 UTC, leesangb commented on src/components/carousel/stories/Pagination.stories.tsx
> +    },
가독성을 위해 인더테이션을 바꿔주시면 좋을것같아요!

2022-09-18 03:55 UTC, LeeSuHa98 commented on src/components/carousel/imageOptimize.tsx
> +    images: string;
src 로 하면 더 직관적일 것 같네요 !!

2022-09-18 04:06 UTC, LeeSuHa98 commented
수정 완료했습니다 ! 머지 진행할게요 !

2022-09-18 08:44 UTC, leesangb approved these changes

2022-09-18 08:44 UTC, merged