Feat/character
sendOwlOrganization/SendOwl-Web pull request #43
Opened 2022-12-28 17:52 UTC by Dev-Guccin

- [x] 자동 스크롤 이동 구현

![2022-12-29-25056](https://user-images.githubusercontent.com/52245525/209852712-f6e689a6-dd66-43f2-9498-41a1c3001920.gif)

2022-12-28 17:53 UTC, Dev-Guccin reviewed
코드가 적절한지 확인부탁드립니다!

2022-12-29 00:28 UTC, leesangb requested changes

2022-12-29 00:28 UTC, leesangb commented on src/components/welcome/Welcome.tsx
> +const MbtiScroll= styled('div')`
스크롤 로직들이 Welcome컴포넌트의 역할이 아니어서 새로운 컴포넌트 파일만들어서 분리해주시면 감사하겠습니다!

2022-12-29 00:28 UTC, leesangb commented on src/components/welcome/Welcome.tsx
> +    useEffect(()=>{
애니메이션은 최대한 css로 처리하는게 성능적으로 좋습니다
https://codepen.io/danedmonds/pen/gMEYwr
이런식으로 구현 해보면 좋을것같아요!

2022-12-29 00:28 UTC, leesangb commented on src/components/welcome/Welcome.tsx
> +                            return <img key={index} src={str}></img>
리액트에서 map을 쓸 때 key는 index로 하면 버그가 생길 수 있습니다
mbti가 이미 유니크하니 그걸로 key값 하면 될것같아요!
참고: https://medium.com/sjk5766/react-%EB%B0%B0%EC%97%B4%EC%9D%98-index%EB%A5%BC-key%EB%A1%9C-%EC%93%B0%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3ce48b3a18fb

2022-12-29 00:37 UTC, Dev-Guccin commented on src/components/welcome/Welcome.tsx
> +const MbtiScroll= styled('div')`
그럼 스크롤 컴퍼넌트를 만들고 mbti 리스트를 props로 내려주는 방식으로 개발하면 될까요?

2022-12-29 02:27 UTC, leesangb commented on src/components/welcome/Welcome.tsx
> +const MbtiScroll= styled('div')`
2가지 방법이 있을것 같습니다
1. mbti상관없이 그냥 어떤이미지를 받든 스크롤애니메이션 하는 컴포넌트를 만들거면 props로 image list(여기선 mbti 캐릭터들)를 받아도 됩니다
2. mbti만 스크롤하는 컴포넌트를 만들거면 해당 컴포넌트 내에서 mbti 캐릭터들을 import해서 쓰면 됩니다

2022-12-31 05:48 UTC, Dev-Guccin commented on src/components/welcome/Welcome.tsx
> +                            return <img key={index} src={str}></img>
수정했습니다!

2022-12-31 08:42 UTC, Dev-Guccin commented on src/components/welcome/Welcome.tsx
> +    useEffect(()=>{
수정했습니다!

2022-12-31 08:58 UTC, leesangb commented on src/components/welcome/Welcome.tsx
> +                    })
이건 사소한거만 조금 더 간결하게 써도 될것같아요!
```
mbti_list.map((mbti) => <img key={mbti} src={`/character/${mbti.toLowerCase()}.svg`} />
```

2022-12-31 09:20 UTC, Dev-Guccin commented on src/components/welcome/Welcome.tsx
> +const MbtiScroll= styled('div')`
2번으로 적용했습니다!

2022-12-31 09:29 UTC, Dev-Guccin commented on src/components/welcome/Welcome.tsx
> +                    })
수정했습니다!

2022-12-31 09:31 UTC, leesangb commented
고생하셨습니다!

2022-12-31 09:32 UTC, leesangb approved these changes

2022-12-31 09:32 UTC, merged