Main 컴포넌트
sendOwlOrganization/SendOwl-Web pull request #5
Opened 2022-04-23 10:33 UTC by LeeSuHa98

- 블라인드 메인화면 클론
- 반응형 컴포넌트 

![main](https://user-images.githubusercontent.com/40999647/164890746-c53570e5-e3c4-416e-956d-0ecaced9d7bf.gif)

2022-04-23 10:58 UTC, leesangb requested changes

2022-04-23 10:58 UTC, leesangb commented on src/components/main/Content.tsx
> +      <Grid display={"flex"}>
`MainContent`에 다른 컴포넌트들을 추가 하게 될테니 `l.80`까지 컴포넌트를 추출해도 좋을 것 같아요

2022-04-23 10:58 UTC, leesangb commented on src/components/main/Content.tsx
> +          <h3>토픽 베스트</h3>
`h3`과 `h5` 태그를 사용한 특별한 이유가 있을까요?

2022-04-23 10:58 UTC, leesangb commented on src/components/main/Main.tsx
> +      <MainHeader/>
`MainHeader`는 나중에 `GlobalLayout` 같은 컴포넌트에 추가하고 `_app.tsx`에서 감싸주면 페이지마다 추가 하지 않아도 됩니당

2022-04-23 10:58 UTC, leesangb commented on src/components/main/MainHeader.tsx
> +        <Button href="/home" color="inherit">
`mui` 컴포넌트로 `href` 링크를 만들게 되면 해당 링크를 누를 때 마다 페이지가 새로고침됩니다.
`next/link`패키지에 있는 컴포넌트를 활용하면 페이지 새로고침 없이 이동하게 할 수 있어요!

해당 문서들 참고하시면 좋을거같아용
- https://github.com/mui/material-ui/blob/af81aae3b292ed180e7652a665fad1be2b38a7b3/examples/nextjs-with-typescript/src/Link.tsx
- https://mui.com/material-ui/guides/routing/#next-js
- https://nextjs.org/docs/api-reference/next/link

2022-04-23 10:58 UTC, leesangb commented on src/components/main/MainHeader.tsx
> +        <Grid
나중에 검색 관련 로직이 들어갈테니 컴포넌트 추출해도 좋을것 같아요!

2022-04-23 23:12 UTC, leesangb commented on src/components/main/MainHeader.tsx
> +        <Button href="/home" color="inherit">
#7 이슈로 대체

2022-04-25 09:40 UTC, LeeSuHa98 commented on src/components/main/Main.tsx
> +      <MainHeader/>
그럼 component/global 폴더 생성하고 index.ts, MainHeader.tsx, (MainFooter.tsx 추가 필요?) 파일 추가하면 되나용 ?
_app.tsx 에 
import {Main} from '../src/components/global' 
....
 <RecoilRoot>
                <ThemeProvider theme={theme}>
                    <CssBaseline/>
                    <Main/>
                    <Component {...pageProps} />
                </ThemeProvider>
            </RecoilRoot>
...
이런식으로 들어가는 건가요 ??

2022-04-25 09:49 UTC, leesangb commented on src/components/main/Main.tsx
> +      <MainHeader/>
네네 이런식으로 하면 될거같아요!

```tsx
<GlobalLayout>
    <Component {...pageProps}/>
</GlobalLayout>
```

그리고 네이밍에서 `Main`보다 `Global` 이 더 좋을것같은게 `Main`하면 메인화면에만 쓰는 레이아웃으로 생각할수도 있을거같아요

2022-04-25 11:35 UTC, LeeSuHa98 commented on src/components/main/Main.tsx
> +      <MainHeader/>
아 ~ 알겠습니다 !!

2022-04-28 07:44 UTC, leesangb commented on src/components/main/Content.tsx
> +    const mobile = useMediaQuery('(max-width: 767px)');
이 부분은 어디에 쓰이는건가용 ?

2022-04-28 07:50 UTC, LeeSuHa98 commented on src/components/main/Content.tsx
> +    const mobile = useMediaQuery('(max-width: 767px)');
이부분 실수로 삭제 안하고 커밋했네요 ! 수정하겠습니당

2022-04-28 07:55 UTC, leesangb requested changes
굳굳 좋네요!
조금만 다듬으시면 될 것 같습니다!
색상 관련 constant들은 테마 작업할 때 같이 추출해보죠!

2022-04-28 07:55 UTC, leesangb commented on src/components/main/Content.tsx
> +    const [isMobile, setIsMobile] = useState('0');
mui 테마에 제공해주는 `xs`, `sm`, `md`, `lg`, `xl`을 재사용해도 좋을거같아용!

2022-04-28 07:55 UTC, leesangb commented on src/components/main/Content.tsx
> +function useEffect(arg0: () => void, arg1: boolean[]) {
이 부분은 잘못 추가하신 것 같아요!

2022-04-28 07:55 UTC, leesangb commented on src/components/search/Search.tsx
> +                className='mobile'
css를 찾지 못했는데 어디에 있나용?

2022-04-28 07:55 UTC, leesangb commented on src/components/search/Search.tsx
> +import Link from 'next/link';
안 쓰시는 import는 지우셔도 될 것 같아요!

2022-04-28 08:00 UTC, LeeSuHa98 commented on src/components/search/Search.tsx
> +                className='mobile'
아 classname 설정한 이유는 모바일이랑 데스크탑 알아보려고 넣은거에요 ! 삭제할게요 !!!

2022-04-28 08:36 UTC, leesangb approved these changes

2022-04-28 08:41 UTC, merged